#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : seatd
Version  : 0.5.0
Release  : 2
URL      : https://git.sr.ht/~kennylevinsen/seatd/archive/0.5.0.tar.gz
Source0  : https://git.sr.ht/~kennylevinsen/seatd/archive/0.5.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: seatd-bin = %{version}-%{release}
Requires: seatd-lib = %{version}-%{release}
Requires: seatd-license = %{version}-%{release}
Requires: seatd-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(scdoc)
BuildRequires : systemd-dev

%description
# seatd and libseat
A minimal seat management daemon, and a universal seat management library.

%package bin
Summary: bin components for the seatd package.
Group: Binaries
Requires: seatd-license = %{version}-%{release}

%description bin
bin components for the seatd package.


%package dev
Summary: dev components for the seatd package.
Group: Development
Requires: seatd-lib = %{version}-%{release}
Requires: seatd-bin = %{version}-%{release}
Provides: seatd-devel = %{version}-%{release}
Requires: seatd = %{version}-%{release}

%description dev
dev components for the seatd package.


%package lib
Summary: lib components for the seatd package.
Group: Libraries
Requires: seatd-license = %{version}-%{release}

%description lib
lib components for the seatd package.


%package license
Summary: license components for the seatd package.
Group: Default

%description license
license components for the seatd package.


%package man
Summary: man components for the seatd package.
Group: Default

%description man
man components for the seatd package.


%prep
%setup -q -n seatd-0.5.0
cd %{_builddir}/seatd-0.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1624636019
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dlogind=enabled  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/seatd
cp %{_builddir}/seatd-0.5.0/LICENSE %{buildroot}/usr/share/package-licenses/seatd/2cde27906a20c716691369eb16c55ae2bcd8b263
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/seatd

%files dev
%defattr(-,root,root,-)
/usr/include/libseat.h
/usr/lib64/libseat.so
/usr/lib64/pkgconfig/libseat.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libseat.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/seatd/2cde27906a20c716691369eb16c55ae2bcd8b263

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/seatd.1
